"""rename department

Revision ID: 146751552707
Revises: 24c8ede56422
Create Date: 2024-10-03 19:35:59.263616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146751552707'
down_revision = '24c8ede56422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")    
    # ### end Alembic commands ###
